//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taksoo.Resource {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TaksooResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TaksooResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Taksoo.Resource.TaksooResource", typeof(TaksooResource).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddressSearch.
        /// </summary>
        internal static string AddressSearch {
            get {
                return ResourceManager.GetString("AddressSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddSelectedAddress.
        /// </summary>
        internal static string AddSelectedAddress {
            get {
                return ResourceManager.GetString("AddSelectedAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ArrivingAfterFiverMin.
        /// </summary>
        internal static string ArrivingAfterFiverMin {
            get {
                return ResourceManager.GetString("ArrivingAfterFiverMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ArrivingJustNow.
        /// </summary>
        internal static string ArrivingJustNow {
            get {
                return ResourceManager.GetString("ArrivingJustNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfirmationCode.
        /// </summary>
        internal static string ConfirmationCode {
            get {
                return ResourceManager.GetString("ConfirmationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfirmNumber.
        /// </summary>
        internal static string ConfirmNumber {
            get {
                return ResourceManager.GetString("ConfirmNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContactInfo.
        /// </summary>
        internal static string ContactInfo {
            get {
                return ResourceManager.GetString("ContactInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost.
        /// </summary>
        internal static string Cost {
            get {
                return ResourceManager.GetString("Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit.
        /// </summary>
        internal static string Credit {
            get {
                return ResourceManager.GetString("Credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        /// adehRules.
        /// </summary>
        internal static string DehkadehRules {
            get {
                return ResourceManager.GetString("DehkadehRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination.
        /// </summary>
        internal static string Destination {
            get {
                return ResourceManager.GetString("Destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DestinationConfirm.
        /// </summary>
        internal static string DestinationConfirm {
            get {
                return ResourceManager.GetString("DestinationConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance.
        /// </summary>
        internal static string Distance {
            get {
                return ResourceManager.GetString("Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DriverNotFound.
        /// </summary>
        internal static string DriverNotFound {
            get {
                return ResourceManager.GetString("DriverNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DuplicateValue.
        /// </summary>
        internal static string DuplicateValue {
            get {
                return ResourceManager.GetString("DuplicateValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EqualNumberValue.
        /// </summary>
        internal static string EqualNumberValue {
            get {
                return ResourceManager.GetString("EqualNumberValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FirstName.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FreeTrip.
        /// </summary>
        internal static string FreeTrip {
            get {
                return ResourceManager.GetString("FreeTrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FreeTripText {
            get {
                return ResourceManager.GetString("FreeTripText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GooglePlayServiceUpdateMessage.
        /// </summary>
        internal static string GooglePlayServiceUpdateMessage {
            get {
                return ResourceManager.GetString("GooglePlayServiceUpdateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GooglePlayServiceUpdateTitle.
        /// </summary>
        internal static string GooglePlayServiceUpdateTitle {
            get {
                return ResourceManager.GetString("GooglePlayServiceUpdateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GreaterThanValue.
        /// </summary>
        internal static string GreaterThanValue {
            get {
                return ResourceManager.GetString("GreaterThanValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GreaterThanValueOrEqualTo.
        /// </summary>
        internal static string GreaterThanValueOrEqualTo {
            get {
                return ResourceManager.GetString("GreaterThanValueOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HashedPassword.
        /// </summary>
        internal static string HashedPassword {
            get {
                return ResourceManager.GetString("HashedPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImCommingNow.
        /// </summary>
        internal static string ImCommingNow {
            get {
                return ResourceManager.GetString("ImCommingNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IncreaseCredit.
        /// </summary>
        internal static string IncreaseCredit {
            get {
                return ResourceManager.GetString("IncreaseCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IncreaseCreditByRecharge.
        /// </summary>
        internal static string IncreaseCreditByRecharge {
            get {
                return ResourceManager.GetString("IncreaseCreditByRecharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase the amount of credit you want.
        /// </summary>
        internal static string Increasetheamountofredityouwant {
            get {
                return ResourceManager.GetString("Increasetheamountofredityouwant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InivitationMessage.
        /// </summary>
        internal static string InivitationMessage {
            get {
                return ResourceManager.GetString("InivitationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InValid.
        /// </summary>
        internal static string InValid {
            get {
                return ResourceManager.GetString("InValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory.
        /// </summary>
        internal static string Inventory {
            get {
                return ResourceManager.GetString("Inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsActive.
        /// </summary>
        internal static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsAuthenticated.
        /// </summary>
        internal static string IsAuthenticated {
            get {
                return ResourceManager.GetString("IsAuthenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastName.
        /// </summary>
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LessThanString.
        /// </summary>
        internal static string LessThanString {
            get {
                return ResourceManager.GetString("LessThanString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LessThanValue.
        /// </summary>
        internal static string LessThanValue {
            get {
                return ResourceManager.GetString("LessThanValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogIn.
        /// </summary>
        internal static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogInDehkadeh.
        /// </summary>
        internal static string LogInDehkadeh {
            get {
                return ResourceManager.GetString("LogInDehkadeh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MessageToDriver.
        /// </summary>
        internal static string MessageToDriver {
            get {
                return ResourceManager.GetString("MessageToDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        internal static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        internal static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PassengerDetails.
        /// </summary>
        internal static string PassengerDetails {
            get {
                return ResourceManager.GetString("PassengerDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PaymentMethod.
        /// </summary>
        internal static string PaymentMethod {
            get {
                return ResourceManager.GetString("PaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PleaseCallMe.
        /// </summary>
        internal static string PleaseCallMe {
            get {
                return ResourceManager.GetString("PleaseCallMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PleaseWait.
        /// </summary>
        internal static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RangeString.
        /// </summary>
        internal static string RangeString {
            get {
                return ResourceManager.GetString("RangeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RangeValue.
        /// </summary>
        internal static string RangeValue {
            get {
                return ResourceManager.GetString("RangeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReagentCodeMustBeSixCharecter.
        /// </summary>
        internal static string ReagentCodeMustBeSixCharecter {
            get {
                return ResourceManager.GetString("ReagentCodeMustBeSixCharecter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReagentCodeOptional.
        /// </summary>
        internal static string ReagentCodeOptional {
            get {
                return ResourceManager.GetString("ReagentCodeOptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReduceCredit.
        /// </summary>
        internal static string ReduceCredit {
            get {
                return ResourceManager.GetString("ReduceCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reducetravelcosts.
        /// </summary>
        internal static string Reducetravelcosts {
            get {
                return ResourceManager.GetString("Reducetravelcosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegisterBefore.
        /// </summary>
        internal static string RegisterBefore {
            get {
                return ResourceManager.GetString("RegisterBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegisterDehkadeh.
        /// </summary>
        internal static string RegisterDehkadeh {
            get {
                return ResourceManager.GetString("RegisterDehkadeh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegisterInDehkadeh.
        /// </summary>
        internal static string RegisterInDehkadeh {
            get {
                return ResourceManager.GetString("RegisterInDehkadeh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        internal static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequredFirstLastName.
        /// </summary>
        internal static string RequredFirstLastName {
            get {
                return ResourceManager.GetString("RequredFirstLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequredFirstName.
        /// </summary>
        internal static string RequredFirstName {
            get {
                return ResourceManager.GetString("RequredFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReSendCode.
        /// </summary>
        internal static string ReSendCode {
            get {
                return ResourceManager.GetString("ReSendCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salt.
        /// </summary>
        internal static string Salt {
            get {
                return ResourceManager.GetString("Salt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SendCode.
        /// </summary>
        internal static string SendCode {
            get {
                return ResourceManager.GetString("SendCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to signout.
        /// </summary>
        internal static string signout {
            get {
                return ResourceManager.GetString("signout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        internal static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SourceConfirm.
        /// </summary>
        internal static string SourceConfirm {
            get {
                return ResourceManager.GetString("SourceConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifications.
        /// </summary>
        internal static string Specifications {
            get {
                return ResourceManager.GetString("Specifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taksoo.
        /// </summary>
        internal static string Taksoo {
            get {
                return ResourceManager.GetString("Taksoo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TotalCost.
        /// </summary>
        internal static string TotalCost {
            get {
                return ResourceManager.GetString("TotalCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TotalDistance.
        /// </summary>
        internal static string TotalDistance {
            get {
                return ResourceManager.GetString("TotalDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TotalTime.
        /// </summary>
        internal static string TotalTime {
            get {
                return ResourceManager.GetString("TotalTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TripCost.
        /// </summary>
        internal static string TripCost {
            get {
                return ResourceManager.GetString("TripCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TripCostToman.
        /// </summary>
        internal static string TripCostToman {
            get {
                return ResourceManager.GetString("TripCostToman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turnover.
        /// </summary>
        internal static string Turnover {
            get {
                return ResourceManager.GetString("Turnover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViewHelpagain.
        /// </summary>
        internal static string ViewHelpagain {
            get {
                return ResourceManager.GetString("ViewHelpagain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WrongInformation.
        /// </summary>
        internal static string WrongInformation {
            get {
                return ResourceManager.GetString("WrongInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YourScoreToDriver.
        /// </summary>
        internal static string YourScoreToDriver {
            get {
                return ResourceManager.GetString("YourScoreToDriver", resourceCulture);
            }
        }
    }
}
